### ISSUE TITLE
Getting NETWORK_FOR_ETHEREUM error

### ISSUE THREAD

**Issue by artall64** [skalenetwork/skale-ima-sdk#2]
After launch,
`tail -f data_dir/all_ima_deploy_mn.txt`
Gives `Please set NETWORK_FOR_ETHEREUM to .env file`

How what config shell edit to start this project on rinkeby.

Also, here is a note:
https://github.com/skalenetwork/skale-ima-sdk/blob/master/.env-sample#L8
Don't change. But the same time here:
https://github.com/skalenetwork/skale-ima-sdk/blob/master/.env-sample#L17
Should it be `rinkeby` If I want to start it on rinkeby ?

**Comment by artall64** [comment]
After I add this variable manually to root `.env` I've got `Error: Mnemonic invalid or undefined`
on `tail -f data_dir/all_ima_deploy_mn.txt`

**Comment by cstrangedk** [comment]
Resolved #3
