### ISSUE TITLE
How to set the SDK_VERSION?

### ISSUE THREAD

**Issue by elthworth** [skalenetwork/skale-ima-sdk#63]
```$ WAIT=True bash scripts/run_sdk.sh```
`Updating skaled configuration file
Will load JSON file "/home/bara/Desktop/Workspace/Skale/skale-ima-sdk/config0.json"...
Did loaded content of JSON file "/home/bara/Desktop/Workspace/Skale/skale-ima-sdk/config0.json", will parse it...
Done, loaded content of JSON file "/home/bara/Desktop/Workspace/Skale/skale-ima-sdk/config0.json".
Updated sChain owner: 0xeF89150C91AcE974eE22862357a5C669cA9F718B
Address 0xeF89150C91AcE974eE22862357a5C669cA9F718B is already in accounts section
Address 0x6d80aAC61F6d92c7F4A3c412850474ba963B698E is already in accounts section
Will load JSON file "/home/bara/Desktop/Workspace/Skale/skale-ima-sdk/conf/fs-artifacts.json"...
Did loaded content of JSON file "/home/bara/Desktop/Workspace/Skale/skale-ima-sdk/conf/fs-artifacts.json", will parse it...
Done, loaded content of JSON file "/home/bara/Desktop/Workspace/Skale/skale-ima-sdk/conf/fs-artifacts.json".
Added contract: 0xD3002000000000000000000000000000000000D3
Added contract: 0xD3001000000000000000000000000000000000D3
Added contract: 0xD3003000000000000000000000000000000000D3
Updated sChain owner in context contract!
Will save JSON file "/home/bara/Desktop/Workspace/Skale/skale-ima-sdk/config0.json"...
Done, saved content of JSON file "/home/bara/Desktop/Workspace/Skale/skale-ima-sdk/config0.json".
Done.
scripts/run_sdk.sh: line 27: SDK_VERSION: Need to set SDK_VERSION`

I am trying to run this SDK to obtain a Skale endpoint, but I got an issue above.
Please help me with it.

**Comment by SKALE-jace** [comment]
After step 3 here in the [docs](https://docs.skale.network/develop/ima-sdk), there needs to be a variable added and the following commands rerun. 

1. add `SDK_VERSION=0.3.0` to your `.env`
2. reexport env variables `export $(grep -v '^#' .env | xargs)`
2. rerun `WAIT=True bash scripts/run_sdk.sh`

**Comment by gannakulikova** [comment]
@elthworth  closing the ticket for now, please let us know if you have any additional questions!
